# Generated by Django 3.0.3 on 2020-10-20 06:49

import blog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='プログラミング', max_length=100, unique=True, verbose_name='カテゴリー名')),
                ('category_type', models.IntegerField(choices=[(1, 'main'), (2, 'sub')], help_text='カテゴリーレベル', verbose_name='カテゴリーレベル')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, default='', max_length=100, null=True, unique=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='blog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='タグ名')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, default='', max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('text', models.TextField(verbose_name='本文')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='サムネイル')),
                ('is_public', models.BooleanField(default=True, verbose_name='公開可能か?')),
                ('likes', models.IntegerField(default=0, verbose_name='いいね')),
                ('description', models.TextField(max_length=130, verbose_name='記事の説明（SEOのmeta関連）')),
                ('keywords', models.CharField(default='Dart,Flutter', max_length=255, verbose_name='記事のキーワード（SEOのmeta関連）')),
                ('viewnumber', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='閲覧数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('category', models.ForeignKey(blank=True, default=blog.models.get_or_create_default_category, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='カテゴリー')),
                ('relation_posts', models.ManyToManyField(blank=True, related_name='_post_relation_posts_+', to='blog.Post', verbose_name='関連記事')),
                ('tags', models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='タグ')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='blog.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('access_at', models.DateField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
